### PR TITLE
GameControllerInput autogenerate

### PR DESCRIPTION
**Pull request by arkms**
GameControllerInput now auto initialize himself, dont need add to any GameObject in scene.
Change the example code with new format.

### CODE REVIEW

**Comment by andre-lima** [comment]
Hello @arkms , do you want me to transfer the ownership of this repository to you? I won't support this project, anyways.

**Comment by arkms** [comment]
I just found it and I think it's great for my students who are starting at Unity and it would be great to support it!

**Comment by andre-lima** [comment]
Awesome. I tried changing the ownership, but since you forked it already, there is a name conflict. If you want it, please either delete or rename  your version so I can transfer it to you. Thanks.

**Comment by arkms** [comment]
Done, i really delete my fork version.

**Comment by andre-lima** [comment]
I think it's done, although I still see it as being mine.

**Comment by arkms** [comment]
Ready!, yeah, it takes a few minutes to finish the transfer. Thanks 👍

**Pull request merged**
